/**
 * MCP Server Auto-Generator.
 * Generates a self-contained MCP server definition (JS module source) from a list of tool schemas.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const OUT_BASE = path.resolve('./data/mcp-servers');

/** Sanitize a server name so it cannot be used for path traversal. */
function sanitizeName(name) {
  // Allow only alphanumerics, hyphens, and underscores
  const safe = String(name).replace(/[^a-zA-Z0-9_-]/g, '_');
  if (!safe || safe === '.' || safe === '..') throw new Error('Invalid server name');
  return safe;
}

/**
 * Generate a MCP server definition and write it to disk.
 * @param {string} name  - server identifier
 * @param {Array}  tools - array of { name, description, schema } objects
 * @returns {{ name, path, tools, status }}
 *   status is always 'scaffold' – handlers throw until the caller fills them in.
 */
function generate(name, tools) {
  const safeName = sanitizeName(name);
  fs.mkdirSync(OUT_BASE, { recursive: true });
  const outPath = path.join(OUT_BASE, `${safeName}.js`);

  const toolsSource = tools.map((t) => {
    const schemaStr = JSON.stringify(t.schema || {}, null, 4)
      .split('\n')
      .join('\n    ');
    const toolNameLiteral = JSON.stringify(String(t.name));
    return `  {
    name: ${toolNameLiteral},
    description: ${JSON.stringify(t.description || '')},
    schema: ${schemaStr},
    handler: async (args) => {
      return {
        ok: false,
        tool: ${toolNameLiteral},
        message: ${toolNameLiteral} + ' has not been customized yet. Replace this generated handler with a real implementation.',
        args: args || {}
      };
    }
  }`;
  });

  const source = `/**
 * Auto-generated MCP server: ${safeName}
 * Generated by QuantumForge mcp/server-gen
 */
'use strict';

module.exports = {
  name: ${JSON.stringify(safeName)},
  tools: [
${toolsSource.join(',\n')}
  ]
};
`;

  fs.writeFileSync(outPath, source, 'utf8');

  return { name: safeName, path: outPath, tools: tools.map((t) => t.name), status: 'scaffold' };
}

module.exports = { generate };
